apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-iycy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-iycy
    app.kubernetes.io/part-of: tkrw-pr712-0075-0025-app
  name: devfile-sample-iycy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-iycy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-iycy
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0025-tenant/tkrw-pr712-0075-0025-app/devfile-sample-iycy@sha256:9c56370cb4c2edfa0165097adf02743e0603cca8ab1fe98d6f44a167e1154391
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
