apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-iycy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0025-tenant/tkrw-pr712-0075-0025-app/devfile-sample-iycy@sha256:9c56370cb4c2edfa0165097adf02743e0603cca8ab1fe98d6f44a167e1154391
        name: my-nodejs
        resources: {}
status: {}
